language: node_js

node_js:
  - stable
addons:
  chrome: stable
before_install:
  - yarn global add @lhci/cli
install:
  - yarn --frozen-lockfile --ignore-optional
script:
  - yarn deploy
after_success:
  - yarn lh
