language: node_js
install:
  - yarn
node_js:
  - stable
addons:
  chrome: stable
before_install:
  - yarn global add @lhci/cli
  - yarn --frozen-lockfile --ignore-optional
script:
  - yarn deploy
after_success:
  - lhci autorun
